application:
  appId: java-ducky
  assetId: ducky-crm
  projectLanguage: Java
  platformVersion: Java 8
  buildSystem: Maven
  riskMatrixRevision: demo-1.1
  sourceFilePattern: ".*\\+\\+\\+.*(\\.java)+.*"
  sensitivePackagePattern: "password"
  fileChangeThreshold: 5

environment:
  enableJira: false
  enableScm: false
  scmOwner: "xenserverarmy"
  scmRepositoryName: "ducky-crm"
  scmBranchName: "master"
  githubApiUrl: "https://api.github.com/repos/"
